enum AuthErrorCode {
  NOT_MATCH = "NOT_MATCH", // password and confirm password not match
  EXISTS_USER = "EXISTS_USER", //user already exists
  INVALID_EMAIL = "INVALID_EMAIL", //invalid email
  VERIFY_EMAIL = "VERIFY_EMAIL", //user need to verify email
  DUPLICATE_LOGIN = "DUPLICATE_LOGIN", //login when not logout yet
  WRONG_PASSWORD = "WRONG_PASSWORD", // provided wrong password
  INVALID_RESET_PASSWORD_TOKEN = "INVALID_RESET_PASSWORD_TOKEN",
  NOT_FOUND_RESET_PASSWORD_TOKEN = "NOT_FOUND_RESET_PASSWORD_TOKEN",
  RESET_PASSWORD_TOKEN_EXPIRED = "RESET_PASSWORD_TOKEN_EXPIRED",
  INVALID_ACCESS_TOKEN = "INVALID_ACCESS_TOKEN",
  INVALID_VERIFY_EMAIL_TOKEN = "INVALID_VERIFY_EMAIL_TOKEN",
  INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
  NOT_FOUND_REFRESH_TOKEN = "NOT_FOUND_REFRESH_TOKEN",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  NOT_FOUND_USER = "NOT_FOUND_USER",
  NOT_FOUND_ACCESS_TOKEN = "NOT_FOUND_ACCESS_TOKEN",
  NOT_LOGIN = "NOT_LOGIN",
  EXPIRE_REFRESH_TOKEN = "EXPIRE_REFRESH_TOKEN",
  EXPIRE_ACCESS_TOKEN = "EXPIRE_ACCESS_TOKEN",
  FAILED_VALIDATE_BODY = "FAILED_VALIDATE_BODY",
  SERVER_INTERNAL_ERROR = "SERVER_INTERNAL_ERROR",
  NOT_FOUND = "NOT_FOUND",
  DATABASE_ERROR = "DATABASE_ERROR",
  FORBIDDEN_ERROR = "FORBIDDEN_ERROR",
}
export default AuthErrorCode;
